apiVersion: apps/v1
kind: Deployment
metadata:
  name: "2048-deployment"
spec:
  selector:
    matchLabels:
      app: "2048"
  replicas: 3
  template:
    metadata:
      labels:
        app: "2048"
    spec:
      containers:
        - image: agrawpri/2048-docker
          imagePullPolicy: Always
          name: "2048"
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: "2048"
  name: "service-2048"
spec:
  ports:
  - port: 80
    protocol: TCP
    nodePort: 31256
  selector:
    app: "2048"
  type: NodePort
status:
  loadBalancer: {}
